# Generated by Django 4.2.3 on 2023-09-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_friendshiprequest_rejected_friendshiprequest_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='viewed',
        ),
    ]
