# Generated by Django 4.2.3 on 2023-07-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a wish category (e.g. Clothes, Jewellery etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the wish', max_length=1000)),
                ('price', models.FloatField(default=0)),
                ('booked', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(help_text='Select a category for this wish', to='wishlist.category')),
            ],
        ),
    ]
