# Generated by Django 4.2.3 on 2023-07-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Wish',
        ),
    ]
