# Generated by Django 4.2.3 on 2023-07-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_rename_book_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
