# Generated by Django 4.2.3 on 2023-08-06 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0004_wish_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='booked',
        ),
        migrations.AddField(
            model_name='wish',
            name='booked_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_wishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_wishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
