# Generated by Django 4.2.3 on 2023-08-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
